---
title: "Example interactive report"
---

```{r example-options, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE
)
```

```{r generate-report}
# only generate it if this is a release version
if (
  length(unlist(strsplit(
    as.character(utils::packageVersion("mantis")),
    "[.]"
  ))) <
    4
) {
  example_prescription_numbers <- mantis::example_prescription_numbers

  filename <-
    mantis::mantis_report(
      df = example_prescription_numbers,
      file = "../../docs/articles/example-prescriptions-interactive.html",
      inputspec = mantis::inputspec(
        timepoint_col = "PrescriptionDate",
        item_cols = c("Antibiotic", "Spectrum", "Location"),
        value_col = "NumberOfPrescriptions",
        tab_col = "Location"
      ),
      outputspec = mantis::outputspec_interactive(),
      report_title = "Example mantis report - interactive",
      dataset_description = "Hover mouse over the graphs to see dates and values. Filter the table by typing into the boxes under the column headings.",
      show_progress = FALSE
    )
}
```

```{css hide-header-logo, echo=FALSE}
img.logo {
	display: none;
	}
```

```{=html}
<iframe src="https://ropensci.github.io/mantis/articles/example-prescriptions-interactive.html" width="100%" height="900">
</iframe>
```

